import mongoose from "mongoose";


/*

{message_id: "496c0f70-e5a6-4d3e-99c2-7d0e1cde3d7d", text: "Hello, how are you?", type: "processed",…}
message_id
:
"496c0f70-e5a6-4d3e-99c2-7d0e1cde3d7d"
speaker
:
"SPEAKER_00"
text
:
"Hello, how are you?"
type
:
"processed"
 */

const conversationsSchema = new mongoose.Schema({
    session: { type: mongoose.Schema.Types.ObjectId, ref: "sessions", required: true },
    message_id: { type: String, required: true }, // id of message, generated by stt service
    speaker: { type: String, required: true },
    text: { type: String, required: true },
    type: { type: String, required: true }
}, {
    timestamps: true
});




const Conversations = mongoose.model("conversations", conversationsSchema);

export default Conversations;